config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

 resources :chorus
 root 'chorus#index'

 resources :users, only: [:show, :index]
 
 resources :questions do
 resources :answers, only: [:create]
 end

end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :user
    belongs_to :question

    validates :body, presence: true, length: { maximum: 1000 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choru.rb
class Choru < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :answers, dependent: :destroy
    belongs_to :user

    
    validates :title, presence: true, length: { maximum: 100 }
    validates :body, length: { maximum: 3000 }
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable,
         :validatable
       


         has_many :chorus, dependent: :destroy
         has_many :questions, dependent: :destroy
         has_many :answers, dependent: :destroy
         validates :name, presence: true
         validates :profile, length: { maximum: 200 }
         mount_uploader :image, ImageUploader         
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    before_action :authenticate_user!

    def create
        @answer = Answer.new(answer_params)
        @answer.user_id = current_user.id
        @answer.question_id = params[:question_id]
        if @answer.save
            redirect_to ("/questions/#{params[:question_id]}")
        else
            @question = Question.find(params[:question_id])
            render"questions/show"
        end
    end


    private
     def answer_params
          params.require(:answer).permit(:body)
     end
    end

    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # 割愛
  
    # deviseコントローラーにストロングパラメータを追加する          
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])

      # アカウント編集の時にnameとprofileのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
    end
  
  end

app/controllers/chorus_controller.rb
class ChorusController < ApplicationController
     before_action :authenticate_user!, only: [:new, :create]
     def  index
        @chorus = Choru.all
        @choru = Choru.new
    end

    def create
        choru = Choru.new(choru_params)
        choru.user_id = current_user.id
        
        if choru.save
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end

    def new
        @choru = Choru.new
    end

    def show
        @choru = Choru.find(params[:id])
    end

    def edit
        @choru = Choru.find(params[:id])
    end

    def update
        choru = Choru.find(params[:id])
        if choru.update(choru_params)
            redirect_to:action => "show", :id => choru.id
        else
            redirect_to:action => "new"
        end

    end

    def destroy
        choru = Choru.find(params[:id])
        choru.destroy
        redirect_to action: :index
    end


    private
    def choru_params
        params.require(:choru).permit(:about, :image, :address, :date, :name)

    end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    def index
        @questions= Question.all
    end
    
    def new
        @question = Question.new
    end
    def create
        question = Question.new(question_params)
        question.user_id = current_user.id

        if question.save
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end

    def show
        @question = Question.find(params[:id])
        @answer = Answer.new
    end

    def edit
        @question = Question.find(params[:id])
    end

    def update
        question = Question.find(params[:id])
        if question.update(question_params)
          redirect_to :action => "show", :id => question.id
        else
          redirect_to :action => "new"
        end
    end

    def destroy
        question = Question.find(params[:id])
        question.destroy
        redirect_to action: :index
    end

    private
     def question_params
        params.require(:question).permit(:title, :body)
      end
     def ensure_current_user
        @question = Question.find_by(id: params[:id])
        if @question.user_id != current_user.id
            redirect_to("/questions/#{@question.id}")
        end
    end
    




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
        @user = User.new
    end

    def new
        @choru = Choru.new
    end


    def edit
        @choru = Choru.find(params[:id])
    end
    
    def update
        choru = Choru.find(params[:id])
        if choru.update(choru_params)
            redirect_to:action => "show", :id => choru.id
        else
            redirect_to:action => "new"
        end

    end

    def show
        @user = User.find(params[:id]) 
    end

    def destroy
        choru = Choru.find(params[:id])
        choru.destroy
        redirect_to action: :index
    end
    
    private
    def choru_params
        params.require(:choru).permit(:about, :image, :address, :date, :name)

    end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chorus_helper.rb
module ChorusHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chorus/edit.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>

<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>投稿編集</title>
</head>

<body>
<div class="container">
  <div class="row">
    <div class="col-md-1">

    </div>
    <div class="col-md-10">
      <h1 class="text-center font-weight-bold pt-5">Edit a post</h1>
<div class="post-container pt-3">
    <%= form_for @choru do |f| %>
           <p><%= f.label:"コンサート名" %> <%= f.text_field :name, class: "col-md-12 form-control" %></p>
           <p><%= f.label:"開催場所" %> <%= f.text_field :address, class: "col-md-12 form-control" %></p>
           <p><%= f.label:"開催日時" %> <%= f.text_field :date, class: "col-md-12 form-control" %></p>
           <p><%= f.label:"演奏内容" %> <%= f.text_area :about, class: "col-md-12 form-control" %></p>
   
           <div class="field">
             <%= f.label :image %>
              <%= f.file_field :image %>
            </div>

            <div class= "actions pt-3" > 
              <%= f.submit "編集する", class: "btn btn-primary" %>
           </div>
    <% end %>  
</div>
<div class="col-md-1">

    </div>
  </div>
</div>

</body>

app/views/chorus/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>ようこそ、歌うたいの広場へ</title>
</head>
<%= stylesheet_link_tag 'index', :media => "all" %>

<body>

<div class="container">
  <div class="header"></div>
  <div class="left">
    <%= image_tag 'pexels-thirdman-6193774.jpg', class:'center', size: '320x606' %>
  <p> <b>うたを愛するすべての人へ</b> </p>
  <p>このサイトは全国の合唱人、歌好きのために作りました。いつの時代も歌が、そして心踊る音楽が、私たちの味方です。</p>
  </div>
  <div class= "center">
    <%= image_tag 'pexels-elina-sazonova-3971983.jpg', class:'center', size: '320x606' %>
   <p> <b>知らなかった団体との出会い</b> </p>
  <p>全国には、多種多様な合唱団があります。あなたの「好き」がきっと見つかるはず</p>
  </div>
  <div class= "right">
    <%= image_tag 'pexels-cottonbro-7520369.jpg', class: 'right', size: '320x606' %>
  <p>  <b>歌を「究める」</b> </p>
  <p>オンライン練習や発声方法など、世代を超えた合唱人の為の、合唱人によるプラットフォーム</p>
  </div>
</div>


<div class="btn">
 <div class= "btn-flat" > 
   <%= link_to "新規登録",new_user_registration_path %>
 </div>
</div>

<div class= "btn-flat2" > 
  <%= link_to "ログイン",new_user_session_path %>
</div>

  
</body>
</html>

app/views/chorus/new.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>新規投稿</title>
</head>
<%= stylesheet_link_tag 'new', :media => "all" %>

<div class="container">
  <div class="row">
    <div class="col-md-1">

    </div>
    <div class="col-md-10">
      <h1 class="text-center font-weight-bold pt-5">新規投稿 </h1>
<div class="post-container pt-3">
    <%= form_for(@choru, :url => { controller:'chorus', action:'create'})do |f| %>
           <p><%= f.label:"コンサート名" %> <%= f.text_field :name, class: "col-md-12 form-control" %></p>
           <p><%= f.label:"開催場所" %> <%= f.text_field :address, class: "col-md-12 form-control" %></p>
           <p><%= f.label:"開催日時" %> <%= f.text_field :date, class: "col-md-12 form-control" %></p>
           <p><%= f.label:"演奏内容" %> <%= f.text_area :about, class: "col-md-12 form-control" %></p>
   
           <div class="field">
             <%= f.label :image %>
              <%= f.file_field :image %>
            </div>
    <div class="actions pt-3">       
       <%= f.submit "送信", class:"btn btn-primary" %>
    </div>
    <% end %>  
</div>
<div class="col-md-1">

    </div>
  </div>
</div>


<div class="btn"  > 
 <a href="/users" class= "btn-circle-flat">投稿一覧に戻る</a>
</div>
</html>

app/views/chorus/show.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>

 <h3>投稿内容</h3>
<div class ="container">
　<div class="post">
    <div class= "text2">
    <p><%= @choru.name %></p>
    <p><%= @choru.address %></p>
    <p><%= @choru.date %></p>
  　<p><%= @choru.about %></p>
  　<p><% @choru.created_at %></p>
  </div>
  <div class= "main">
   <%= image_tag @choru.image_url, size: "250x354" if @choru.image? %>
　</div>
</div>

<div class="btn" >
 <a href="/users" class= "btn-circle-flat" >投稿する</a>
</div>
  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppChorus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous">
    </script>
    <%= stylesheet_link_tag 'application', :media => "all", 'data-turbolinks-track': 'reload'%>
    
  </head>
 
  <body>
  <% if user_signed_in? %>
    <header>
      <h1><%= link_to 'The singing square', chorus_path %></h1>
    <div class="header-list">
      <ul>
          <li><a href="/users">団体一覧</a></li>
          <li><a href="/questions">質問一覧</a></li>
          <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
      </ul>
    </div>
   </header>

  <% else %>
   <header>
   <h1><%= link_to 'The singing square', chorus_path %></h1>
   <div class="header-list">
   <ul>
         <li><a href="/users">団体一覧</a></li>
         <li><a href="/questions">質問一覧</a></li>
         <li><a href="/users/sign_up">Sign up</a></li>
         <li><a href="/users/sign_in">Log in</a></li>
       
   </ul>
 </div>
</header>
<% end %>

   
   <main>
      <%= yield %>
      <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
   </main>
   
  </body>
</html>

app/views/questions/edit.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>

<div class="container">
<div class="container">
  <div class="row">
    <div class="col-md-1">

    </div>
    <div class="col-md-10">
      <h1 class="text-center font-weight-bold pt-5">Edit a question</h1>
<div class="post-container pt-3">
　　　<%= form_for @question do |f| %>
           <p><%= f.label:"タイトル" %> <%= f.text_field :title, class: "col-md-12 form-control" %></p>
           <p><%= f.label:"内容" %> <%= f.text_area :body, class: "col-md-12 form-control" %></p>
   
            <div class= "actions pt-3" > 
              <%= f.submit "編集する", class: "btn btn-primary" %>
           </div>
    <% end %>  
</div>
<div class="col-md-1">

    </div>
  </div>
</div>

app/views/questions/index.html.erb
<%= stylesheet_link_tag 'questions', :media => "all" %>

<body>

<div class="loader-wrap">
  <div class="loader">Loading..♪</div>
</div>

<div class="questions-container">
<h3>質問投稿一覧</h3>
   <% @questions.each do |t| %>
     <div class="question">
       <div class= "main-box">
        <div class="left-container">
         <%= t.user.name %>
         </div>
        <div class="center-container"><%= t.title %></div>
        <div class="right-container">
         <%= link_to "詳細へ", question_path(t.id) %>
        </div>
       </div>
     </div>
   <% end %> 
 </div>

 <div class="btn">
  <a href="/questions/new" class="btn-circle-flat">新規投稿する</a>
 </div>

 <script>
$(function(){
	var loader = $('.loader-wrap');

	//ページの読み込みが完了したらアニメーションを非表示
	$(window).on('load',function(){
		loader.fadeOut();
	});

	//ページの読み込みが完了してなくても3秒後にアニメーションを非表示にする
	setTimeout(function(){
		loader.fadeOut();
	},5000);
});
</script>

 </body>

 

 

app/views/questions/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>

<div class="container">
  <div class="row">
    <div class="col-md-1">

    </div>
 <div class="col-md-10">
    <h1 class="text-center font-weight-bold pt-5">質問投稿</h1>

　　<%= form_with(model: @question, local: true) do |f| %>
 　　<div class= "title">
   　　<%= f.label :title, "タイトル" %><br>
   　　<%= f.text_field :title, class: "col-md-12 form-control" %>
 　　</div>
 　　<div class= "body">
  　　　<%= f.label :body, "本文" %><br>
  　　　<%= f.text_area :body,class: "col-md-12 form-control", size: "10x10" %>
 　　</div>
    <div class ="actions">
  　　　<%= f.submit"投稿する", class: "btn btn-primary" %>
    </div>
　　<% end %>
    
    </div>
    <div class="col-md-1">

    </div>
  </div>
</div>

app/views/questions/show.html.erb
<%= stylesheet_link_tag 'answers', :media => "all" %>
<body>
<div class="container">
  <div class="row">
    <div class="col-md-1">
   
    </div>
    <div class="col-md-10">

<h1 class="text-center font-weight-bold" pt-5>質問詳細</h1>

<div class= "question pt-3" >
  <p><%= @question.title %></p>
  <p><%= @question.body %></p>
</div>

<div class="link1">
 <%= link_to "投稿を編集する", edit_question_path(@question.id) %>
</div>

<div class="answer pt-3">
 <%= form_with(model: [@question, @answer], local: true) do |f| %>
    <div>
     <br><%= f.label :body, "回答" %></br>
     <%= f.text_area :body, class:"col-md-12 form-control" %>
    </div>
    <div class="action pt-3">
     <%= f.submit "回答する", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

<div class="post-answer">
 <% @question.answers.each do |answer| %>
    <p><%= answer.body %></p>
  <% end %>
</div>

<div class="btn">
  <a href="/questions" class="btn-circle-flat">質問一覧に戻る</a>
</div>
<div class="col-md-1">

    </div>
  </div>
</div>
</body>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
 <meta charset="utf-8">
 <title>user-index</title>
 </head>
 <%= stylesheet_link_tag 'users', :media => "all" %>

 <body>

 <div class="loader-wrap">
  <div class="loader">Loading..♪</div>
</div>

  <div class= "title">
   <h2>団体一覧</h2>
  </div>

  <div class="user-container">
    <% @users.each do |t| %>
     <div class="user">
       <div>
         <%= link_to user_path(t.id) do %> 
              <%= t.name %>
          <% end %>
       </div>
       <div class="img">
         <%= link_to user_path(t.id) do %> 
            <%= image_tag t.image_url, size: "255x155" if t.image? %>
         <% end %>
       </div>
      
      </div>
    <% end %>
 </div>

 <script>
$(function(){
	var loader = $('.loader-wrap');

	//ページの読み込みが完了したらアニメーションを非表示
	$(window).on('load',function(){
		loader.fadeOut();
	});

	//ページの読み込みが完了してなくても3秒後にアニメーションを非表示にする
	setTimeout(function(){
		loader.fadeOut();
	},5000);
});
</script>


</body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", user_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="ja">
 <head>
 <meta charset="UTF-8">
 <%= stylesheet_link_tag 'show', :media => "all" %>
 <title>HelloUserShow</title>
 </head>

<body>
  

<div class= "box1">
  <div class="text">
     <h5>Name:<%= @user.name %></h5>
    <p><%= @user.profile %></p>
  </div>
  <div class="user-image">
   <%= image_tag @user.image_url, size: "300x240" if @user.image? %>
  </div>
  <section>
   <% if current_user.id == @user.id %>
     <a href="/users/edit" class="btn_01">プロフィールを編集する</a>
   <% end %>
  </section>
</div>


<% @user.chorus.each do |t| %>
  <div class="post">
     <div class="text2">
        <p><%= t.name %></p>
        <p><%= t.address %></p>
        <p><%= t.date %></p>
        <p><%= t.about %></p>
      </div>
    <div class="main">
       <%= image_tag t.image_url, size: "250x354" if t.image? %></div>
      </div>

    <div class="link2">
      <% if current_user.id == @user.id %>
        <%= link_to "投稿を編集する", edit_choru_path(t.id) %>
        <%= link_to "削除する", choru_path(t.id), method: :delete %>
      <% end %>
    </div>
  </div>
<% end %>





<div class="btn"> 
  <% if current_user.id == @user.id %>
    <a href="/chorus/new" class= "btn-circle-flat">新規投稿</a>
  <% end %>
</div>

 </body>
</html>